// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pbuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CustomLogicClient is the client API for CustomLogic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomLogicClient interface {
	Request(ctx context.Context, in *ReqContext, opts ...grpc.CallOption) (*RespContext, error)
}

type customLogicClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomLogicClient(cc grpc.ClientConnInterface) CustomLogicClient {
	return &customLogicClient{cc}
}

func (c *customLogicClient) Request(ctx context.Context, in *ReqContext, opts ...grpc.CallOption) (*RespContext, error) {
	out := new(RespContext)
	err := c.cc.Invoke(ctx, "/CustomLogic/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomLogicServer is the server API for CustomLogic service.
// All implementations must embed UnimplementedCustomLogicServer
// for forward compatibility
type CustomLogicServer interface {
	Request(context.Context, *ReqContext) (*RespContext, error)
	mustEmbedUnimplementedCustomLogicServer()
}

// UnimplementedCustomLogicServer must be embedded to have forward compatible implementations.
type UnimplementedCustomLogicServer struct {
}

func (UnimplementedCustomLogicServer) Request(context.Context, *ReqContext) (*RespContext, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedCustomLogicServer) mustEmbedUnimplementedCustomLogicServer() {}

// UnsafeCustomLogicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomLogicServer will
// result in compilation errors.
type UnsafeCustomLogicServer interface {
	mustEmbedUnimplementedCustomLogicServer()
}

func RegisterCustomLogicServer(s grpc.ServiceRegistrar, srv CustomLogicServer) {
	s.RegisterService(&CustomLogic_ServiceDesc, srv)
}

func _CustomLogic_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomLogicServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CustomLogic/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomLogicServer).Request(ctx, req.(*ReqContext))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomLogic_ServiceDesc is the grpc.ServiceDesc for CustomLogic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomLogic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CustomLogic",
	HandlerType: (*CustomLogicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _CustomLogic_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "restype.proto",
}
