// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: restype.proto

package pbuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqContext_Method int32

const (
	ReqContext_GET    ReqContext_Method = 0
	ReqContext_POST   ReqContext_Method = 1
	ReqContext_PUT    ReqContext_Method = 2
	ReqContext_DELETE ReqContext_Method = 3
)

// Enum value maps for ReqContext_Method.
var (
	ReqContext_Method_name = map[int32]string{
		0: "GET",
		1: "POST",
		2: "PUT",
		3: "DELETE",
	}
	ReqContext_Method_value = map[string]int32{
		"GET":    0,
		"POST":   1,
		"PUT":    2,
		"DELETE": 3,
	}
)

func (x ReqContext_Method) Enum() *ReqContext_Method {
	p := new(ReqContext_Method)
	*p = x
	return p
}

func (x ReqContext_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqContext_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_restype_proto_enumTypes[0].Descriptor()
}

func (ReqContext_Method) Type() protoreflect.EnumType {
	return &file_restype_proto_enumTypes[0]
}

func (x ReqContext_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqContext_Method.Descriptor instead.
func (ReqContext_Method) EnumDescriptor() ([]byte, []int) {
	return file_restype_proto_rawDescGZIP(), []int{2, 0}
}

type RespContext_PayloadType int32

const (
	RespContext_JSON RespContext_PayloadType = 0
	RespContext_RAW  RespContext_PayloadType = 1
	RespContext_XML  RespContext_PayloadType = 2
)

// Enum value maps for RespContext_PayloadType.
var (
	RespContext_PayloadType_name = map[int32]string{
		0: "JSON",
		1: "RAW",
		2: "XML",
	}
	RespContext_PayloadType_value = map[string]int32{
		"JSON": 0,
		"RAW":  1,
		"XML":  2,
	}
)

func (x RespContext_PayloadType) Enum() *RespContext_PayloadType {
	p := new(RespContext_PayloadType)
	*p = x
	return p
}

func (x RespContext_PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespContext_PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_restype_proto_enumTypes[1].Descriptor()
}

func (RespContext_PayloadType) Type() protoreflect.EnumType {
	return &file_restype_proto_enumTypes[1]
}

func (x RespContext_PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespContext_PayloadType.Descriptor instead.
func (RespContext_PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_restype_proto_rawDescGZIP(), []int{3, 0}
}

type Strings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *Strings) Reset() {
	*x = Strings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restype_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Strings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strings) ProtoMessage() {}

func (x *Strings) ProtoReflect() protoreflect.Message {
	mi := &file_restype_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strings.ProtoReflect.Descriptor instead.
func (*Strings) Descriptor() ([]byte, []int) {
	return file_restype_proto_rawDescGZIP(), []int{0}
}

func (x *Strings) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Param struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Param) Reset() {
	*x = Param{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restype_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_restype_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_restype_proto_rawDescGZIP(), []int{1}
}

func (x *Param) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Param) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ReqContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index   int32               `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Method  ReqContext_Method   `protobuf:"varint,2,opt,name=method,proto3,enum=ReqContext_Method" json:"method,omitempty"`
	Headers map[string]*Strings `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Params  []*Param            `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty"`
	Queries map[string]*Strings `protobuf:"bytes,5,rep,name=queries,proto3" json:"queries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body    []byte              `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *ReqContext) Reset() {
	*x = ReqContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restype_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqContext) ProtoMessage() {}

func (x *ReqContext) ProtoReflect() protoreflect.Message {
	mi := &file_restype_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqContext.ProtoReflect.Descriptor instead.
func (*ReqContext) Descriptor() ([]byte, []int) {
	return file_restype_proto_rawDescGZIP(), []int{2}
}

func (x *ReqContext) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ReqContext) GetMethod() ReqContext_Method {
	if x != nil {
		return x.Method
	}
	return ReqContext_GET
}

func (x *ReqContext) GetHeaders() map[string]*Strings {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ReqContext) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ReqContext) GetQueries() map[string]*Strings {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *ReqContext) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type RespContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32                   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Type    RespContext_PayloadType `protobuf:"varint,2,opt,name=type,proto3,enum=RespContext_PayloadType" json:"type,omitempty"`
	Payload []byte                  `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *RespContext) Reset() {
	*x = RespContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restype_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespContext) ProtoMessage() {}

func (x *RespContext) ProtoReflect() protoreflect.Message {
	mi := &file_restype_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespContext.ProtoReflect.Descriptor instead.
func (*RespContext) Descriptor() ([]byte, []int) {
	return file_restype_proto_rawDescGZIP(), []int{3}
}

func (x *RespContext) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RespContext) GetType() RespContext_PayloadType {
	if x != nil {
		return x.Type
	}
	return RespContext_JSON
}

func (x *RespContext) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_restype_proto protoreflect.FileDescriptor

var file_restype_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x65, 0x73, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x21, 0x0a, 0x07, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x22, 0x2f, 0x0a, 0x05, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0xa8, 0x03, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2a, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x52, 0x65, 0x71, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x32, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x52, 0x65, 0x71, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x1e, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x32, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x72,
	0x69, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x52, 0x65, 0x71, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x1a, 0x44, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x1e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x44, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x69, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x30, 0x0a, 0x06,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x55, 0x54,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x22, 0x94,
	0x01, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x18, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x29, 0x0a, 0x0b, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x53, 0x4f,
	0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x41, 0x57, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03,
	0x58, 0x4d, 0x4c, 0x10, 0x02, 0x32, 0x35, 0x0a, 0x0b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4c,
	0x6f, 0x67, 0x69, 0x63, 0x12, 0x26, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0b, 0x2e, 0x52, 0x65, 0x71, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x1a, 0x0c, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c,
	0x72, 0x65, 0x73, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x70, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_restype_proto_rawDescOnce sync.Once
	file_restype_proto_rawDescData = file_restype_proto_rawDesc
)

func file_restype_proto_rawDescGZIP() []byte {
	file_restype_proto_rawDescOnce.Do(func() {
		file_restype_proto_rawDescData = protoimpl.X.CompressGZIP(file_restype_proto_rawDescData)
	})
	return file_restype_proto_rawDescData
}

var file_restype_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_restype_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_restype_proto_goTypes = []interface{}{
	(ReqContext_Method)(0),       // 0: ReqContext.Method
	(RespContext_PayloadType)(0), // 1: RespContext.PayloadType
	(*Strings)(nil),              // 2: Strings
	(*Param)(nil),                // 3: Param
	(*ReqContext)(nil),           // 4: ReqContext
	(*RespContext)(nil),          // 5: RespContext
	nil,                          // 6: ReqContext.HeadersEntry
	nil,                          // 7: ReqContext.QueriesEntry
}
var file_restype_proto_depIdxs = []int32{
	0, // 0: ReqContext.method:type_name -> ReqContext.Method
	6, // 1: ReqContext.headers:type_name -> ReqContext.HeadersEntry
	3, // 2: ReqContext.params:type_name -> Param
	7, // 3: ReqContext.queries:type_name -> ReqContext.QueriesEntry
	1, // 4: RespContext.type:type_name -> RespContext.PayloadType
	2, // 5: ReqContext.HeadersEntry.value:type_name -> Strings
	2, // 6: ReqContext.QueriesEntry.value:type_name -> Strings
	4, // 7: CustomLogic.Request:input_type -> ReqContext
	5, // 8: CustomLogic.Request:output_type -> RespContext
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_restype_proto_init() }
func file_restype_proto_init() {
	if File_restype_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_restype_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Strings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restype_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Param); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restype_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restype_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_restype_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restype_proto_goTypes,
		DependencyIndexes: file_restype_proto_depIdxs,
		EnumInfos:         file_restype_proto_enumTypes,
		MessageInfos:      file_restype_proto_msgTypes,
	}.Build()
	File_restype_proto = out.File
	file_restype_proto_rawDesc = nil
	file_restype_proto_goTypes = nil
	file_restype_proto_depIdxs = nil
}
